### ISSUE TITLE
Add bzip3 support

### ISSUE THREAD

**Issue by kspalaiologos** [ib/xarchiver#163]
[bzip3](https://github.com/kspalaiologos/bzip3) is a spiritual successor to bzip2; generally features better compression ratio. It's packaged for all major Linux distributions (Debian, Void, Gentoo, Arch, Alpine, Gentoo, NixOS, etc..) so compatibility/support should be rather wide.

Two rather notable differences from other compressors are the fact that bzip3 can utilise multithreading while compressing (using a fixed amount of jobs) and doesn't support the concept of levels (a block size needs to be passed to the compressor instead).

I recommend block sizes of 8M, 16M, 32M, 64M, 128M, 256M, 511M to map to levels 1-7. As the memory usage tends to be around 6*N (where N is the block size), caution is required to not exhaust the operating system's memory (level 7 will consume around 3GB of memory per compression thread).

**Comment by ib** [comment]
Any plans to get a MIME type?

**Comment by ib** [comment]
Let's try to [get one](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/issues/195).

**Comment by ib** [comment]
Xarchiver does not care about file extensions, it only checks magic numbers to recognize archive types.

A MIME type only increases the convenience of opening archives, i.e. archives can be opened from a file manager instead of from xarchiver itself.

I am aware of the problem with changing the mime type for bzip2, but the previous handling of bzip/bzip2 in shared-mime-info is just wrong.

As long as the proposed new MIME types are not part of shared-mime-info, xarchiver will not support them (yet).

**Comment by ib** [comment]
There is now a [MIME type](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/commit/c99df0f4d3df7f1327e8e3c6cb33c2321c5b7e1c).
