### ISSUE TITLE
Argument list too long error

### ISSUE THREAD

**Issue by mirh** [ib/xarchiver#43]
Can't run the archiver executable: child process execution «/usr/bin/unzip» (argument list too long)

[Example](https://github.com/torvalds/linux/archive/master.zip).

**Comment by ib** [comment]
Please describe more detailed what you are doing (especially your drag and drop).

**Comment by mirh** [comment]
Drag and drop that archive (the [usual way](https://github.com/ib/xarchiver/issues/41#issuecomment-352089375)) and you get the error above.

**Comment by gituser789** [comment]
Same thing here.
Making archive by using the right-click menu leads to the same error.

Using the command line works fine with the same files:
```
tar cf archive.tar folder_with_many_files
```

I am using version `0.5.4.14`. Not the latest, but this issue hasnt been closed since a while.

**Comment by Saijin-Naib** [comment]
I also experienced this behavior using 0.5.20 on Alpine Linux edge v3.18 x86_64 when attempting to archive my /home/ directory in the following three ways:  
1) Drag/Drop /home/
2) Right-click /home/ in Thunar and Archive
3) Create archive, Add Files, choose /home/

Home has the following statistics:  
![image](https://user-images.githubusercontent.com/19295950/236234268-69cfbef7-6c00-483c-bb07-dac4efa5ac1a.png)

The archiving attempts that didn't error out on argument list too long (I believe using 7zip backend) also would take all of my memory during the time it was enumerating the files to add to the archive, so 4GB RAM and 4GB SWAP, whereupon it would crash due to OOM.

**Comment by ib** [comment]
- Extraction
Still working on.
- Archive creation
No way to fix this for right-click and Thunar's archive interface, which requires a list of all files.
But drag/drop as well as adding files from within xarchiver now works, if the compressor/archiver command line program supports it.

**Comment by Saijin-Naib** [comment]
Sorry I missed your tag in May. 

Is the Thunar Archive Function limitation something with prior art on how to address? 

Pipe everything into a CSV and pass that? 

Open an Issue with them?

**Comment by ib** [comment]
@Saijin-Naib 

I am getting old.

Thunar right-click also works, if you have configured `Allow subdirs with clipboard and drag-and-drop` in xarchiver (see 37122609e7d7df36fa4b36640cf7f116a053a73c).

**Comment by Saijin-Naib** [comment]
All good! Know the feeling. 

Does 3712260 do anything to help limit max memory usage? 

If this goes into a tagged release I should be able to build and test on my laptop to see if it OOM or not, and if it can complete the archival.

**Comment by ib** [comment]
> Does https://github.com/ib/xarchiver/commit/37122609e7d7df36fa4b36640cf7f116a053a73c do anything to help limit max memory usage?

No, it just ensures that the argument list is as short as possible. Xarchiver has no control over the memory usage of the compressor/archiver command line program.

**Comment by ib** [comment]
- Extraction
Works now.
- Deletion
Works now.
