### ISSUE TITLE
Xarchiver fails to extract multi-part password protected 7z files

### ISSUE THREAD

**Issue by apoleon** [ib/xarchiver#92]
This is Debian bug https://bugs.debian.org/959914

Just quoting the bug report here again:

When i create a multi-part 7z with password, the opening of the archive just failed, where using command line 7z tool work fine.

An example :
$ 7z a -ptest -v10b "test.7z" smallfile.example

So i get my multi-part 7z. Now if i open it with xarchiver, that's what i get in output window :
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=fr_FR.UTF-8,Utf16=on,HugeFiles=on,64 bits

Scanning the drive for archives:
1 file, 10 bytes (1 KiB)

Listing archive: /mnt/TEMPORAIRE/test.7z.001

Enter password (will not be echoed):--
Path = /mnt/TEMPORAIRE/test.7z.001Type = Split
Physical Size = 10
Volumes = 23
Total Physical Size = 230

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
                    .....          230          230  test.7z
------------------- ----- ------------ ------------  ------------------------
                                   230          230  1 files
----------
Path = test.7z
Open ERROR: Can not open the file as [7z] archive

------------------- ----- ------------ ------------  ------------------------
                                   230          230  1 files

Archives: 1
Volumes: 23
Total archives size: 230

Errors: 1

---------------------------------------

Now testing the archive with the commande line tool :
$ 7z t -ptest test.7z.001

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=fr_FR.UTF-8,Utf16=on,HugeFiles=on,64 bits

Scanning the drive for archives:
1 file, 10 bytes (1 KiB)

Testing archive: test.7z.001
--        
Path = test.7z.001
Type = Split
Physical Size = 10
Volumes = 23
Total Physical Size = 230
----
Path = test.7z
Size = 230
--
Path = test.7z
Type = 7z
Physical Size = 230
Headers Size = 182
Method = LZMA2:12 7zAES
Solid = -
Blocks = 1

Everything is Ok

Size:       85
Compressed: 230

---------------------------------------

7z x work fine too.

**Comment by ib** [comment]
Fixed.

**Comment by Ski-lleR** [comment]
Hi, i'm the one who reported the bug on debian.

Actually the fix is ok for passworded multi-part 7z, but it fail like before when using encrypted header (-mhe).

The error message is exactly the same in Xarchiver :
Open ERROR: Can not open the file as [7z] archive

Just made a test from cli to be sure :
7z a -v25m -p12345 -mhe "test_splitted.7z" testfile
7z t -p12345 test_splitted.7z.001

Testing archive: test_splitted.7z.001
--         
Path = test_splitted.7z.001
Type = Split
Physical Size = 26214400
Volumes = 5
Total Physical Size = 107122425
----
Path = test_splitted.7z
Size = 107122425
--
Path = test_splitted.7z
Type = 7z
Physical Size = 107122425
Headers Size = 185
Method = LZMA2:24 7zAES
Solid = -
Blocks = 1

Everything is Ok

**Comment by ib** [comment]
I'll have to investigate this further.

**Comment by ib** [comment]
Fixed.
